data=read.csv("2007.csv")
modelA<-lm(TNRR~CEE+MHTE+GEE+I+LFAE+RDE+RRD, data=data)
modelB<-lm(NGR~CEE+MHTE+GEE+I+LFAE+RDE+RRD, data=data)
modelC<-lm(TNRR~CEE+HTE+GEE+I+LFAE+RDE+RRD, data=data)
modelD<-lm(NGR~CEE+HTE+GEE+I+LFAE+RDE+RRD, data=data)
